living_room_nightlight:
  alias: 'Living Room 01 Nightlight'
  description: 'Activates Hue nightlight scene and turns off CASA dimmers.'
  sequence:
    - service: scene.turn_on
      target:
        entity_id: scene.hue_living_room_nightlight
    - service: light.turn_off
      target:
        entity_id:
          - light.comet
          - light.cupid
  mode: single
