living_room_full:
  alias: 'Living Room 05 Full'
  description: 'Activates Hue full scene and sets all CASA dimmers to 100%.'
  sequence:
    - service: scene.turn_on
      target:
        entity_id: scene.hue_living_room_full
    - service: light.turn_on
      target:
        entity_id:
          - light.comet
          - light.cupid
      data:
        brightness_pct: 100
  mode: single
