nursery_nursing:
  alias: "Nursery Nursing"
  description: "Activates Hue nursing scene and turns off overhead."
  sequence:
    - service: scene.turn_on
      target:
        entity_id: scene.hue_nursery_nursing
    - service: light.turn_off
      target:
        entity_id: light.nursery_overhead
  mode: single
