- id: '1760722187456'
  alias: Play Sonos Favorite
  description: ''
  triggers:
    - webhook_id: play_sonos_favorite_3c45d9df52f76f69d
      trigger: webhook
      allowed_methods:
        - POST
        - PUT
      local_only: true
  actions:
    - data:
        favorite_id: '{{ trigger.json.favorite_id }}'
        favorite_name: '{{ trigger.json.favorite_name }}'
        speaker: "{{ trigger.json.speaker | default('media_player.office') }}"
        volume: '{{ trigger.json.volume | default(20) }}'
      action: script.play_sonos_favorite
  mode: single
- id: '1760991819246'
  alias: Sonos Play/Pause Toggle
  description: ''
  triggers:
    - trigger: webhook
      allowed_methods:
        - POST
        - PUT
      local_only: true
      webhook_id: sonos_play_pause_toggle-9xN2v3SJ3dBxK2nwqg-8HFRz
  conditions: []
  actions:
    - action: script.sonos_play_pause_toggle
      metadata: {}
      data:
        speaker: media_player.office
  mode: single
- id: '1761213613754'
  alias: 'Sonos: Set Volume'
  description: ''
  triggers:
    - trigger: webhook
      allowed_methods:
        - POST
        - PUT
      local_only: true
      webhook_id: sonos_volume-DH_Vfuo9vkcaeGEpOkC_GMP2
  conditions: []
  actions:
    - action: script.sonos_volume
      metadata: {}
      data:
        speaker: "{{ trigger.json.speaker | default('media_player.office') }}"
        volume: '{{ trigger.json.volume | default(20) }}'
  mode: single
