# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
scene: !include scenes.yaml

# debugging Sonos
#logger:
#  default: warning
#  logs:
#    homeassistant.components.sonos: debug
#    homeassistant.components.media_player: debug
